library(ggplot2)
library(ggthemes)
library(forecast)
library(tseries)
library(xts)


#loading the dataset
US_candy_production <- read.csv("C:/Users/chand/OneDrive/Desktop/candy_production.csv")

#checking the class of the dataset
str(US_candy_production)


# Assign more meaningful variable names
colnames(US_candy_production)<-c("Date","candy_production")

US_candy_production$date<-as.Date(US_candy_production$Date, format="%Y-%m-%d")
CandyXTS<- xts(US_candy_production[-1], US_candy_production[[1]])
CandyTS<- ts(US_candy_production$candy_production, start=c(1972,1),end=c(2017,8), frequency=12 )

# Convert data into time series dataset
attach(US_candy_production)
candyts<-ts(candy_production,c(1972,1),c(2017,8),12)
str(candyts)


#EDA
# Take a peek at the dataset
candyts



# Checking are there anu missing values
sum(is.na(candyts))

# Checking the frequency of the time series data
frequency(candyts)

# Checking the cycle of the time series
cycle(candyts)

# Review the summary statistics
summary(candyts)


options(repr.plot.width=18, repr.plot.height=6)
plot(candyts,xlab="Year", ylab = "Candy Production in percentage",main="Monthly US Candy Production from 1972 to 2017")
autoplot(candyts) + labs(x ="Year", y = "Candy Production in percentage", title="Monthly US Candy Production from 1972 to 2017") + theme_classic()


# Plotting the raw data using the base plot function
plot(candyts,xlab="Year", ylab = "Candy Production as (%) of 2012 Production",main="Monthly US Candy Production from 1972 to 2017")


autoplot(candyts) + labs(x ="Year", y = "Candy Production as (%) of 2012 Production", title="Monthly US Candy Production from 1972 to 2017") + theme_classic()


#boxplot function to see any seasonal effects
boxplot(candyts~cycle(candyts),xlab="Month", ylab = "Candy Production as (%) of 2012 Production" ,main ="Monthly US Candy Production from 1972 to 2017")


boxplot(CandyTS)

#The ACF plot shows evidence of no-stationarity
ggAcf(CandyTS)



#Test of Stationarity
adf.test(candyts)

#To see Decompose Random Time Series 
decom_candyts$random


